---
title: "Gamer Time"
date: 2018-02-28
---

title: My resume
author: Mikhail Ottewell
email: m.ottewell112@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey! My name is Mikhail and I am an aspiring Computer Science and 
  Mathematics student, who wishes to pursue a Computer Science Engineering
  Degree. I would be very glad if you could look over my resume below!

# social links
twitter_username: N/A (Don't have twitter)
github_username:  @MOttewell

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
